# fly.toml app configuration file generated for word-whimsy on 2023-09-26T09:02:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "word-whimsy"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
